# Generated by Django 5.2.3 on 2025-06-15 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instagram_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("full_name", models.CharField(max_length=151)),
                ("followers", models.PositiveIntegerField(blank=True, null=True)),
                ("posts", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.ImageField(blank=True, null=True, upload_to="instagram/"),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstagramPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_url", models.URLField()),
                ("caption", models.TextField(blank=True, null=True)),
                ("media_url", models.URLField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("reel", "Reel"),
                            ("carousel", "Carousel"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=50,
                    ),
                ),
                ("likes", models.PositiveIntegerField(blank=True, null=True)),
                ("comments", models.PositiveIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("shortcode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_posts",
                        to="instaapp.instagram_user",
                    ),
                ),
            ],
        ),
    ]
