# Generated by Django 5.2.3 on 2025-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instaapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagrampost",
            name="thumbnail_url",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
